version: '3'

services:

  source_db:
    build:
      dockerfile: build/postgres/Dockerfile
      context: .
    environment: 
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - '5432:5432'

  target_db:
    build:
      dockerfile: build/postgres/Dockerfile
      context: .
    environment: 
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - '6432:5432'

  demo_service:
    build:
      dockerfile: build/demo-service/Dockerfile
      context: .
    environment:
      - DB_HOST=source_db
      - DB_PORT=5432
      - DB_NAME=demo
      - DB_USER=demo
      - DB_PASS=demo
    entrypoint: |
      sh -c '
      until nc -w 1 -z source_db 5432; do
        echo "Waiting for db... sleeping"
        sleep 2
      done
      warp-pipe-demo'
    ports:
      - '8080:8080'
    depends_on:
      - source_db
      - target_db
